-- MySQL Script generated by MySQL Workbench
-- Sat May  1 02:29:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_todo_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_todo_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_todo_test` DEFAULT CHARACTER SET utf8 ;
USE `db_todo_test` ;

-- -----------------------------------------------------
-- Table `db_todo_test`.`avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`avatar` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`avatar` (
  `id` TINYINT(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `name` VARCHAR(100) NOT NULL COMMENT 'Наименование',
  `url` VARCHAR(200) NOT NULL COMMENT 'Ссылка',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`employee` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`employee` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'Никнейм',
  `username` VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Имя',
  `password` VARCHAR(250) NOT NULL,
  `date_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата создания',
  `curator_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор куратор',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Последнее обновление',
  `email` VARCHAR(150) NOT NULL DEFAULT '' COMMENT 'Email',
  `avatar_id` TINYINT(5) UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Идентификатор аватара',
  `actived` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Активен',
  `deleted` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Удалён',
  `rate` DOUBLE(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Рейтинг',
  PRIMARY KEY (`id`),
  INDEX `curator_employee_id` (`curator_id` ASC) VISIBLE,
  INDEX `avatar_id` (`avatar_id` ASC) VISIBLE,
  CONSTRAINT `employee_ibfk_1`
    FOREIGN KEY (`curator_id`)
    REFERENCES `db_todo_test`.`employee` (`id`),
  CONSTRAINT `employee_ibfk_2`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `db_todo_test`.`avatar` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`employee_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`employee_type` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`employee_type` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `name` VARCHAR(100) NOT NULL COMMENT 'Наименование',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`project_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`project_type` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`project_type` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `name` VARCHAR(100) NOT NULL COMMENT 'Наименование',
  `description` VARCHAR(250) NOT NULL COMMENT 'Описание',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`project` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`project` (
  `id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор',
  `project_type_id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'Тип проекта',
  `name` VARCHAR(100) NOT NULL COMMENT 'Наименование',
  `prefix` VARCHAR(3) NOT NULL COMMENT 'Префикс задач',
  `description` VARCHAR(250) NOT NULL COMMENT 'Описание',
  `date_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата создания',
  `author_id` INT(10) UNSIGNED NOT NULL COMMENT 'Создатель сотрудник',
  `avatar_id` TINYINT(5) UNSIGNED NOT NULL COMMENT 'Аватар проекта',
  `actived` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Активен',
  `deleted` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Удалён',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Обновлён',
  PRIMARY KEY (`id`),
  INDEX `project_type_id` (`project_type_id` ASC) VISIBLE,
  INDEX `author_employee_id` (`author_id` ASC) VISIBLE,
  INDEX `avatar_id` (`avatar_id` ASC) VISIBLE,
  CONSTRAINT `project_ibfk_1`
    FOREIGN KEY (`project_type_id`)
    REFERENCES `db_todo_test`.`project_type` (`id`),
  CONSTRAINT `project_ibfk_2`
    FOREIGN KEY (`author_id`)
    REFERENCES `db_todo_test`.`employee` (`id`),
  CONSTRAINT `project_ibfk_3`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `db_todo_test`.`avatar` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`project_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`project_employee` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`project_employee` (
  `project_id` INT(8) UNSIGNED NOT NULL,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `employee_type_id` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `employee_id`),
  INDEX `employee_type_id` (`employee_type_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `project_employee_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_todo_test`.`project` (`id`),
  CONSTRAINT `project_employee_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_todo_test`.`employee` (`id`),
  CONSTRAINT `project_employee_ibfk_3`
    FOREIGN KEY (`employee_type_id`)
    REFERENCES `db_todo_test`.`employee_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Менеджеры с доступными проектами';


-- -----------------------------------------------------
-- Table `db_todo_test`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`tag` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`tag` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`task_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`task_status` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`task_status` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NOT NULL DEFAULT '' COMMENT 'Описание',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`task` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`task` (
  `date_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Дата создания',
  `project_id` INT(8) UNSIGNED NOT NULL COMMENT 'Идентификатор проекта',
  `id` INT(8) UNSIGNED ZEROFILL NOT NULL COMMENT 'Идентификатор задачи',
  `parent_id` INT(8) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `name` VARCHAR(150) NOT NULL COMMENT 'Наименование задачи',
  `description` VARCHAR(250) NOT NULL COMMENT 'Описание задачи',
  `author_id` INT(10) UNSIGNED NOT NULL COMMENT 'Автор задачи',
  `executor_id` INT(10) UNSIGNED NOT NULL COMMENT 'Исполнитель',
  `task_status_id` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Статус задачи',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`, `id`),
  INDEX `author_id` (`author_id` ASC) VISIBLE,
  INDEX `task_status_id` (`task_status_id` ASC) VISIBLE,
  INDEX `parent_id` (`parent_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC, `parent_id` ASC) VISIBLE,
  INDEX `executor_id` (`executor_id` ASC) VISIBLE,
  INDEX `task_ibfk_2` (`project_id` ASC, `author_id` ASC) VISIBLE,
  INDEX `project_id_2` (`project_id` ASC, `executor_id` ASC) VISIBLE,
  CONSTRAINT `task_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_todo_test`.`project` (`id`),
  CONSTRAINT `task_ibfk_2`
    FOREIGN KEY (`project_id` , `author_id`)
    REFERENCES `db_todo_test`.`project_employee` (`project_id` , `employee_id`),
  CONSTRAINT `task_ibfk_3`
    FOREIGN KEY (`task_status_id`)
    REFERENCES `db_todo_test`.`task_status` (`id`),
  CONSTRAINT `task_ibfk_4`
    FOREIGN KEY (`project_id` , `parent_id`)
    REFERENCES `db_todo_test`.`task` (`project_id` , `id`),
  CONSTRAINT `task_ibfk_5`
    FOREIGN KEY (`project_id` , `executor_id`)
    REFERENCES `db_todo_test`.`project_employee` (`project_id` , `employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`task_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`task_comment` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`task_comment` (
  `date_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT(8) UNSIGNED NOT NULL,
  `project_id` INT(8) UNSIGNED NOT NULL,
  `task_id` INT(8) UNSIGNED ZEROFILL NOT NULL,
  `comment` VARCHAR(250) NOT NULL,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`task_id`, `project_id`, `id`),
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC, `task_id` ASC) VISIBLE,
  CONSTRAINT `task_comment_ibfk_1`
    FOREIGN KEY (`project_id` , `task_id`)
    REFERENCES `db_todo_test`.`task` (`project_id` , `id`),
  CONSTRAINT `task_comment_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_todo_test`.`employee` (`id`),
  CONSTRAINT `task_comment_ibfk_3`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_todo_test`.`project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`task_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`task_employee` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`task_employee` (
  `project_id` INT(8) UNSIGNED NOT NULL,
  `task_id` INT(8) UNSIGNED ZEROFILL NOT NULL,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `task_id`, `employee_id`),
  INDEX `project_id` (`project_id` ASC, `employee_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `task_employee_ibfk_1`
    FOREIGN KEY (`project_id` , `task_id`)
    REFERENCES `db_todo_test`.`task` (`project_id` , `id`),
  CONSTRAINT `task_employee_ibfk_2`
    FOREIGN KEY (`project_id` , `employee_id`)
    REFERENCES `db_todo_test`.`project_employee` (`project_id` , `employee_id`),
  CONSTRAINT `task_employee_ibfk_3`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_todo_test`.`project` (`id`),
  CONSTRAINT `task_employee_ibfk_4`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_todo_test`.`employee` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`task_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`task_file` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`task_file` (
  `project_id` INT(8) UNSIGNED NOT NULL,
  `task_id` INT(8) UNSIGNED ZEROFILL NOT NULL,
  `id` INT(10) UNSIGNED NOT NULL,
  `task_comment_id` INT(8) UNSIGNED NULL DEFAULT NULL,
  `filename` VARCHAR(200) NOT NULL,
  `date_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `employee_id` INT(10) UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY USING BTREE (`project_id`, `task_id`, `id`),
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `task_comment_id` (`task_comment_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC, `task_id` ASC, `task_comment_id` ASC) VISIBLE,
  CONSTRAINT `task_file_ibfk_3`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_todo_test`.`employee` (`id`),
  CONSTRAINT `task_file_ibfk_4`
    FOREIGN KEY (`project_id` , `task_id`)
    REFERENCES `db_todo_test`.`task` (`project_id` , `id`),
  CONSTRAINT `task_file_ibfk_5`
    FOREIGN KEY (`project_id` , `task_id` , `task_comment_id`)
    REFERENCES `db_todo_test`.`task_comment` (`project_id` , `task_id` , `id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_todo_test`.`task_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_todo_test`.`task_tag` ;

CREATE TABLE IF NOT EXISTS `db_todo_test`.`task_tag` (
  `project_id` INT(8) UNSIGNED NOT NULL,
  `task_id` INT(8) UNSIGNED ZEROFILL NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`project_id`, `task_id`, `name`),
  INDEX `name` (`name` ASC) VISIBLE,
  CONSTRAINT `task_tag_ibfk_1`
    FOREIGN KEY (`project_id` , `task_id`)
    REFERENCES `db_todo_test`.`task` (`project_id` , `id`),
  CONSTRAINT `task_tag_ibfk_2`
    FOREIGN KEY (`name`)
    REFERENCES `db_todo_test`.`tag` (`name`),
  CONSTRAINT `task_tag_ibfk_3`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_todo_test`.`project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;