# Generated by Django 3.2.6 on 2021-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_avatar',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_curator',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_avatar,',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_author',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_projecttype,',
        ),
        migrations.RemoveIndex(
            model_name='projectemployee',
            name='projectemployee_employeetype',
        ),
        migrations.RemoveIndex(
            model_name='projectemployee',
            name='projectemployee_employee',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_author',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_taskstatus',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_parent',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_project_parent',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_executor',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_project_author',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_project_executor',
        ),
        migrations.RemoveIndex(
            model_name='taskcomment',
            name='taskcomment_employee',
        ),
        migrations.RemoveIndex(
            model_name='taskcomment',
            name='taskcomment_project_task',
        ),
        migrations.RemoveIndex(
            model_name='taskemployee',
            name='taskemployee_project_employee',
        ),
        migrations.RemoveIndex(
            model_name='taskemployee',
            name='taskemployee_employee',
        ),
        migrations.RemoveIndex(
            model_name='taskfile',
            name='taskfile_employee',
        ),
        migrations.RemoveIndex(
            model_name='taskfile',
            name='taskfile_task_comment',
        ),
        migrations.RemoveIndex(
            model_name='taskfile',
            name='taskfile_project_task_taskcom',
        ),
        migrations.RemoveIndex(
            model_name='tasktag',
            name='taskstag_name',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['avatar_id'], name='employee_avatar_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['curator_id'], name='employee_curator_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['avatar_id'], name='project_avatar_idx,'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['author_id'], name='project_author_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type_id'], name='project_projecttype_idx,'),
        ),
        migrations.AddIndex(
            model_name='projectemployee',
            index=models.Index(fields=['employee_type_id'], name='projectemployee_employeetype_idx'),
        ),
        migrations.AddIndex(
            model_name='projectemployee',
            index=models.Index(fields=['employee_id'], name='projectemployee_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['author_id'], name='task_author_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_status_id'], name='task_taskstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_id'], name='task_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project_id', 'parent_id'], name='task_project_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['executor_id'], name='task_executor_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project_id', 'author_id'], name='task_project_author_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project_id', 'executor_id'], name='task_project_executor_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['employee_id'], name='taskcomment_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['project_id', 'task_id'], name='taskcomment_project_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskemployee',
            index=models.Index(fields=['project_id', 'employee_id'], name='taskemployee_project_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='taskemployee',
            index=models.Index(fields=['employee_id'], name='taskemployee_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['employee_id'], name='taskfile_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['task_comment_id'], name='taskfile_task_comment_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['project_id', 'task_id', 'task_comment_id'], name='taskfile_project_task_taskcomment_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['name'], name='taskstag_name_idx'),
        ),
    ]
