# Generated by Django 3.2.6 on 2021-09-05 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_remove_employee_extend_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.avatar', verbose_name='Идентификатор аватара'),
        ),
        migrations.AddField(
            model_name='user',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Идентификатор куратор'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='Рэйтинг'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['avatar_id'], name='employee_avatar_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['curator_id'], name='employee_curator_idx'),
        ),
    ]
